### ISSUE TITLE
Assessment report - empty substances

### ISSUE THREAD

**Issue by vedina** [ideaconsult/Toxtree.js#159] opened 2015-11-16 16:38 UTC
Please fix the "null" strings

![image](https://cloud.githubusercontent.com/assets/211190/11188038/aa913b42-8c91-11e5-9c4e-78f33e92368c.png)

**Comment by gonzomir** [comment] 2015-11-23 13:56
I can't replicate this bug, can you send me more info, please? A link to a bundle will be great.

**Comment by vedina** [comment] 2015-11-24 10:54
[bundle 9](https://apps.ideaconsult.net/data/ui/assessment_report?bundle_uri=https%3A%2F%2Fapps.ideaconsult.net%2Fdata%2Fbundle%2F9)

**Comment by gonzomir** [comment] 2015-11-25 08:24
This looks like duplicate of #139 and it is fixed in commit 9c9409e. Are these changes deployed?

**Comment by vedina** [comment] 2015-11-25 08:27
#139 is about the HTML rendering, it is indeed fixed. The changes are deployed. The screenshot above is from the DOCX report.

**Comment by gonzomir** [comment] 2015-11-25 08:43
But the data for the DOCX is gathered from the rendered HTML, so if there are no "null" strings rendered, they should not appear in the report.

In the provided bundle example there are "null"s in the substance names.

Found the problem - it comes from commit 75fe90c.

**Comment by vedina** [comment] 2015-11-25 08:46
ok, can you fix the new `linkeddata` function?  We need the substance names to be linked to the study, not plain string as before.

**Comment by gonzomir** [comment] 2015-11-25 08:57
The fix is in the default configuration on toxsubstance.js. Since we need the name to be linked, when it is null, we display a dash.

**Closed** 2015-11-25 08:59 UTC
Labels: bug
